// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	models "movie-review/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// MovieRepository is an autogenerated mock type for the MovieRepository type
type MovieRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, movie
func (_m *MovieRepository) Create(ctx context.Context, movie *models.Movie) error {
	ret := _m.Called(ctx, movie)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Movie) error); ok {
		r0 = rf(ctx, movie)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MovieRepository) Delete(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: ctx
func (_m *MovieRepository) GetAll(ctx context.Context) ([]models.Movie, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []models.Movie
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]models.Movie, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []models.Movie); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Movie)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllGenres provides a mock function with given fields: ctx
func (_m *MovieRepository) GetAllGenres(ctx context.Context) ([]string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllGenres")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MovieRepository) GetByID(ctx context.Context, id int) (*models.Movie, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Movie
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*models.Movie, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *models.Movie); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Movie)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchMovies provides a mock function with given fields: ctx, query, yearFrom, yearTo, genres, hasComment, offset, limit
func (_m *MovieRepository) SearchMovies(ctx context.Context, query string, yearFrom int, yearTo int, genres []string, hasComment *bool, offset int, limit int) ([]models.Movie, error) {
	ret := _m.Called(ctx, query, yearFrom, yearTo, genres, hasComment, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for SearchMovies")
	}

	var r0 []models.Movie
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int, []string, *bool, int, int) ([]models.Movie, error)); ok {
		return rf(ctx, query, yearFrom, yearTo, genres, hasComment, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int, []string, *bool, int, int) []models.Movie); ok {
		r0 = rf(ctx, query, yearFrom, yearTo, genres, hasComment, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Movie)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int, []string, *bool, int, int) error); ok {
		r1 = rf(ctx, query, yearFrom, yearTo, genres, hasComment, offset, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, movie
func (_m *MovieRepository) Update(ctx context.Context, movie *models.Movie) error {
	ret := _m.Called(ctx, movie)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Movie) error); ok {
		r0 = rf(ctx, movie)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMovieRepository creates a new instance of MovieRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMovieRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MovieRepository {
	mock := &MovieRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
