// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"

	models "movie-review/internal/models"
)

// MovieService is an autogenerated mock type for the MovieService type
type MovieService struct {
	mock.Mock
}

// CreateMovie provides a mock function with given fields: ctx, name, file, fileName, genres, year, description, rating, worldRating, comment
func (_m *MovieService) CreateMovie(ctx context.Context, name string, file io.Reader, fileName string, genres []string, year int, description string, rating int, worldRating float32, comment string) (*models.MovieResponse, error) {
	ret := _m.Called(ctx, name, file, fileName, genres, year, description, rating, worldRating, comment)

	if len(ret) == 0 {
		panic("no return value specified for CreateMovie")
	}

	var r0 *models.MovieResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader, string, []string, int, string, int, float32, string) (*models.MovieResponse, error)); ok {
		return rf(ctx, name, file, fileName, genres, year, description, rating, worldRating, comment)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader, string, []string, int, string, int, float32, string) *models.MovieResponse); ok {
		r0 = rf(ctx, name, file, fileName, genres, year, description, rating, worldRating, comment)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.MovieResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, io.Reader, string, []string, int, string, int, float32, string) error); ok {
		r1 = rf(ctx, name, file, fileName, genres, year, description, rating, worldRating, comment)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteMovie provides a mock function with given fields: ctx, id
func (_m *MovieService) DeleteMovie(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMovie")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllGenres provides a mock function with given fields: ctx
func (_m *MovieService) GetAllGenres(ctx context.Context) ([]string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllGenres")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllMovies provides a mock function with given fields: ctx
func (_m *MovieService) GetAllMovies(ctx context.Context) ([]models.MovieResponse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllMovies")
	}

	var r0 []models.MovieResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]models.MovieResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []models.MovieResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.MovieResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMovieByID provides a mock function with given fields: ctx, id
func (_m *MovieService) GetMovieByID(ctx context.Context, id int) (*models.MovieResponse, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetMovieByID")
	}

	var r0 *models.MovieResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*models.MovieResponse, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *models.MovieResponse); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.MovieResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchMovies provides a mock function with given fields: ctx, query, yearFrom, yearTo, genres, hasComment, offset, limit
func (_m *MovieService) SearchMovies(ctx context.Context, query string, yearFrom int, yearTo int, genres []string, hasComment *bool, offset int, limit int) ([]models.MovieResponse, error) {
	ret := _m.Called(ctx, query, yearFrom, yearTo, genres, hasComment, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for SearchMovies")
	}

	var r0 []models.MovieResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int, []string, *bool, int, int) ([]models.MovieResponse, error)); ok {
		return rf(ctx, query, yearFrom, yearTo, genres, hasComment, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int, []string, *bool, int, int) []models.MovieResponse); ok {
		r0 = rf(ctx, query, yearFrom, yearTo, genres, hasComment, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.MovieResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int, []string, *bool, int, int) error); ok {
		r1 = rf(ctx, query, yearFrom, yearTo, genres, hasComment, offset, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateMovie provides a mock function with given fields: ctx, id, name, file, fileName, genres, year, description, rating, worldRating, comment
func (_m *MovieService) UpdateMovie(ctx context.Context, id int, name string, file io.Reader, fileName string, genres []string, year int, description string, rating int, worldRating float32, comment string) (*models.MovieResponse, error) {
	ret := _m.Called(ctx, id, name, file, fileName, genres, year, description, rating, worldRating, comment)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMovie")
	}

	var r0 *models.MovieResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, string, io.Reader, string, []string, int, string, int, float32, string) (*models.MovieResponse, error)); ok {
		return rf(ctx, id, name, file, fileName, genres, year, description, rating, worldRating, comment)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, string, io.Reader, string, []string, int, string, int, float32, string) *models.MovieResponse); ok {
		r0 = rf(ctx, id, name, file, fileName, genres, year, description, rating, worldRating, comment)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.MovieResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, string, io.Reader, string, []string, int, string, int, float32, string) error); ok {
		r1 = rf(ctx, id, name, file, fileName, genres, year, description, rating, worldRating, comment)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMovieService creates a new instance of MovieService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMovieService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MovieService {
	mock := &MovieService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
